#!/usr/bin/env python3
"""Build a Heimdall server modpack (.zip) from the mods installed on this server.

Each package in mods.lock.json is checked against Hexium, then Thunderstore.
When every installed DLL is identical to the official package of the same
version, the mod becomes a manifest dependency (downloaded at install time).
Otherwise (unpublished, or modified locally) its folders are bundled.

Configuration is bundled only with --with-config, and never the anticheat
folder or files whose names suggest credentials.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'deploy'))
import modpack  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'servicos' / 'painel'))
import hostos  # noqa: E402

SENSITIVE = ('webhook', 'token', 'secret', 'password', 'senha', 'moderator', 'admin')
SKIP_CONFIG_DIRS = {'AzuAntiCheat'}


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def installed_dlls(game: Path, package_id: str) -> dict[str, str]:
    found = {}
    for kind in ('plugins', 'patchers'):
        folder = game / 'BepInEx' / kind / package_id
        if folder.is_dir():
            for dll in folder.rglob('*.dll'):
                found[f'{kind}/{dll.relative_to(folder).as_posix()}'] = sha(dll.read_bytes())
    return found


def official_dlls(owner: str, name: str, version: str, cache: Path) -> dict[str, set[str]] | None:
    try:
        _, selected, source = modpack._metadata(owner, name, version, modpack._get_json)
    except modpack.ModpackError:
        return None
    url = str(selected.get('download_url') or '')
    if source == 'thunderstore' and not url:
        url = f'https://thunderstore.io/package/download/{owner}/{name}/{version}/'
    archive = cache / f'{owner}-{name}-{version}.zip'
    if not archive.is_file():
        modpack.download(url, archive)
    by_name: dict[str, set[str]] = {}
    with zipfile.ZipFile(archive) as bundle:
        for member in bundle.namelist():
            if member.lower().endswith('.dll'):
                by_name.setdefault(member.replace('\\', '/').rsplit('/', 1)[-1], set()).add(sha(bundle.read(member)))
    return by_name


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('output', type=Path, help='destination .zip')
    parser.add_argument('--game', type=Path, default=hostos.env_path('HEIMDALL_VALHEIM_DIR') / 'current')
    parser.add_argument('--config-dir', type=Path, default=hostos.env_path('HEIMDALL_VALHEIM_DIR') / 'config' / 'BepInEx')
    parser.add_argument('--author', default='MyTeam')
    parser.add_argument('--name', default='ServerPack')
    parser.add_argument('--version', default='1.0.0')
    parser.add_argument('--description', default='Server modpack generated by Heimdall Nexus.')
    parser.add_argument('--with-config', action='store_true', help='bundle BepInEx configuration files')
    parser.add_argument('--cache', type=Path, default=hostos.env_path('HEIMDALL_MODPACK_CACHE'))
    args = parser.parse_args()
    if args.output.suffix.lower() != '.zip':
        parser.error('output must end with .zip')
    for value in (args.author, args.name):
        if not modpack.PART.fullmatch(value):
            parser.error(f'invalid name part: {value}')
    if not modpack.VERSION.fullmatch(args.version):
        parser.error('invalid version')

    lock = json.loads((args.game / 'mods.lock.json').read_text(encoding='utf-8'))
    args.cache.mkdir(parents=True, exist_ok=True)
    dependencies, bundled = [], []
    for package_id, entry in sorted(lock.get('packages', {}).items()):
        version = str(entry.get('version') or '')
        mine = installed_dlls(args.game, package_id)
        owner, dash, name = package_id.partition('-')
        official = None
        if dash and modpack.PART.fullmatch(owner) and modpack.PART.fullmatch(name) \
                and modpack.VERSION.fullmatch(version):
            print(f'checking {package_id} {version}…', flush=True)
            official = official_dlls(owner, name, version, args.cache)
        identical = official is not None and all(
            digest in official.get(Path(path).name, set()) for path, digest in mine.items())
        if identical:
            dependencies.append(f'{package_id}-{version}')
        else:
            reason = 'not published' if official is None else 'differs from the official package'
            bundled.append((package_id, reason))

    manifest = {'author': args.author, 'name': args.name, 'version_number': args.version,
                'description': args.description, 'website_url': '', 'dependencies': dependencies}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temp = args.output.with_suffix('.zip.partial')
    with zipfile.ZipFile(temp, 'w', zipfile.ZIP_DEFLATED) as bundle:
        bundle.writestr('manifest.json', json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
        for package_id, _ in bundled:
            for kind in ('plugins', 'patchers'):
                folder = args.game / 'BepInEx' / kind / package_id
                if folder.is_dir():
                    for file in sorted(folder.rglob('*')):
                        if file.is_file() and not file.is_symlink():
                            bundle.write(file, f'{kind}/{package_id}/{file.relative_to(folder).as_posix()}')
        skipped_config = []
        if args.with_config and args.config_dir.is_dir():
            for file in sorted(args.config_dir.rglob('*')):
                relative = file.relative_to(args.config_dir)
                if not file.is_file() or file.is_symlink():
                    continue
                if relative.parts[0] in SKIP_CONFIG_DIRS or any(w in file.name.lower() for w in SENSITIVE):
                    skipped_config.append(relative.as_posix())
                    continue
                bundle.write(file, f'config/{relative.as_posix()}')
    temp.replace(args.output)
    args.output.chmod(0o600)

    print(f'\nWrote {args.output} ({args.output.stat().st_size / 1048576:.1f} MB)')
    print(f'Dependencies from Hexium/Thunderstore: {len(dependencies)}')
    print(f'Bundled in the zip: {len(bundled)}')
    for package_id, reason in bundled:
        print(f'  {package_id}: {reason}')
    if args.with_config:
        print(f'Config files left out for safety: {", ".join(skipped_config) or "none"}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
